### ISSUE TITLE
Maidroid compatibility.

### ISSUE THREAD

**Issue by mazes-80** [AtlanteFr/BeterFarming#3]
Hi Atlante.

Thanks for opening a git repository.
Support for BetterFarming is quite ready in maidroid mod, I didn't looked further since last time we chatted, but I remember I had to expose more things from within your mod to allow droids to plant/harvest your crops.
I hope I'll open some PR soon

**Comment by AtlanteFr** [comment]
C'est a dire ? J'ai pas tous compris xD

**Comment by mazes-80** [comment]
Ah, ok older versions exposed place_param2, which is never used by farming mod, but maidroid still copy this option.
So their placements of seeds were quite funiky.

Now that you dropped them I just [commited](https://gitlab.com/mazes_80/maidroid/-/commit/fcdf1fc8db778b7c48c8ce710aca4a4bfbcf630b)
